packages:
  - 'packages/*'

catalogs:
  default:
    line-column: ^1.0.2
    prettier: ^3.3.2
    unocss: ^0.64.1
    unplugin-auto-import: ^0.18.5
    vscode-uri: ^3.0.8

  compiler:
    '@babel/parser': ^7.24.0
    '@babel/types': ^7.24.0
    ts-morph: ^25.0.0
  cli:
    '@changesets/cli': ^2.27.7
    typescript: ~5.7.3
  vue-libs:
    '@vue/shared': ^3.5.13
    '@vue/test-utils': ^2.4.6
    vue: ^3.5.13
    vue-tsc: ~2.1.10
    '@vue/compiler-dom': ^3.4.38
    '@vue/compiler-ssr': ^3.4.38
    '@vue/language-core': ~2.2.4
    '@vue/language-service': ~2.2.4
  nuxt-libs:
    nuxt: ^3.15.0
    '@nuxt/kit': ^3.15.0
    '@nuxt/schema': ^3.15.0
    '@nuxt/module-builder': ^1.0.1
    '@nuxt/devtools': ^1.6.1
    '@nuxt/eslint-config': ^0.7.1
    '@nuxt/test-utils': ^3.14.4
  volar:
    '@volar/language-core': ~2.4.8
    '@volar/language-server': ~2.4.8
    '@volar/language-service': ~2.4.8
    '@volar/typescript': ~2.4.8
    '@volar/vscode': ~2.4.8
    volar-service-css: ~0.0.62
    volar-service-emmet: ~0.0.62
    volar-service-html: ~0.0.62
    volar-service-typescript: ~0.0.62
  eslint-libs:
    eslint: ~9.10.0
    '@typescript-eslint/parser': ~8.15.0
    '@typescript-eslint/types': ~8.15.0
    '@typescript-eslint/utils': ~8.15.0
    '@typescript-eslint/scope-manager': ~8.15.0
    '@typescript-eslint/typescript-estree': ~8.15.0
  vite-ecosystem:
    vite: ^6.0.0
    vitest: ^3.0.0
    vite-plugin-inspect: ^0.8.8
  types:
    '@types/node': ^20.11.27
    '@types/hash-sum': ^1.0.0
    '@types/line-column': ^1.0.0
    '@types/jsdom': ^21.1.7
